name: Breakfast Bot

on:
  schedule:
    - cron: '*/5 5-8 * * *'  # Every 5 minutes from 6:00 to 8:59 UK time
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
      GOOGLE_DRIVE_FOLDER_ID: 11QV7pggur2rI0AM2cKfhAOswtFTZgM42
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
      EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib

      - name: Run Breakfast Bot
        run: python run_bot.py
